### ISSUE TITLE
force quitting after phone receives MMS

### ISSUE THREAD

**Issue by regaladys** [youngj/EnvayaSMS#22] opened 2012-03-09 03:01 UTC
EnvayaSMS force quits after phone receives an MMS message. Envaya restarts and logs do not indicate receiving an MMS.

**Comment by youngj** [comment] 2012-03-09 04:36
What version of Android does your phone have? (Settings -> About phone -> Firmware version)

If someone experiencing this bug has the Android SDK installed on their computer, they could connect the phone and use "adb logcat" to get the stack trace for the exception ... that would help me figure out how to fix it.

Android does not have an official API for apps to interact with MMS, so it is possible that MMS would break in different versions of Android from what I tested with.

**Comment by regaladys** [comment] 2012-03-09 04:38
Android version 2.3.6
Kernel version 2.6.35.7

**Comment by mfb** [comment] 2012-03-10 05:15
I have also seen a couple of crashes while receiving MMS messages, on Android 2.3.4. Both times upon receiving a large high-res picture that I sent to myself.. sent it to myself again and was able to process it without a crash.

**Comment by youngj** [comment] 2012-03-10 05:42
Interesting. The only Android phone I have at the moment is running Android 2.1. And the largest images I've tested with are around 35 KB (haven't seen any crashes yet). How large are the files you're sending?

Unless I can find some way to reproduce the crash myself, I would need someone to send me a stack trace of the exception that causes the crash. Basically the steps are:
- install the Android SDK on your computer from http://developer.android.com/sdk/index.html 
- connect your Android phone to your computer in USB debugging mode
- send a MMS to your Android phone that causes a crash
- immediately after the crash, run "adb logcat" (adb is in the Android SDK platform tools directory)
- post the logcat output, or at least the entire exception stack trace (there should be a few lines like "at org.envaya.sms.....")

**Comment by mfb** [comment] 2012-03-10 06:54
The message size that is causing a crash pretty consistently is 1208 KB for the sent message and 406 KB for the received message (according to "View message details" in the messaging app) - I sent it to myself so there are two entries (and I guess the photo was automatically reduced to a smaller file size)

**Comment by mfb** [comment] 2012-03-10 07:53
Here is a sample crash. Note it does not always crash. In fact, after being unable to reproduce the crash, I rebooted my phone, and then was able to make it crash again...

03-09 23:45:33.055  2020  2705 D EnvayaSMS: New MMS id=215 in inbox
03-09 23:45:33.055  2020  2705 W dalvikvm: threadid=17: thread exiting with uncaught exception (group=0x40018560)
03-09 23:45:33.063  2020  2705 E AndroidRuntime: FATAL EXCEPTION: IntentService[CheckMmsInboxService]
03-09 23:45:33.063  2020  2705 E AndroidRuntime: java.lang.NullPointerException
03-09 23:45:33.063  2020  2705 E AndroidRuntime:    at org.envaya.sms.App.isForwardablePhoneNumber(App.java:689)
03-09 23:45:33.063  2020  2705 E AndroidRuntime:    at org.envaya.sms.IncomingMessage.isForwardable(IncomingMessage.java:46)
03-09 23:45:33.063  2020  2705 E AndroidRuntime:    at org.envaya.sms.CheckMmsInboxService.onHandleIntent(CheckMmsInboxService.java:46)
03-09 23:45:33.063  2020  2705 E AndroidRuntime:    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:59)
03-09 23:45:33.063  2020  2705 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:99)
03-09 23:45:33.063  2020  2705 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:130)
03-09 23:45:33.063  2020  2705 E AndroidRuntime:    at android.os.HandlerThread.run(HandlerThread.java:60)
03-09 23:45:33.079  1310  1457 W ActivityManager:   Force finishing activity org.envaya.sms/.ui.Main
03-09 23:45:33.220  1310  1340 I ActivityManager: Resumed Activity: org.envaya.sms/.ui.Main totalTime: 5606 ms
03-09 23:45:33.352  2126  2632 I Transaction: MMS-STATUS-DURATION, result=1, uri=content://mms/inbox/215, trans id=11E1122338E000008540000101, bytes sent=0, bytes rec=406602, type=0, created=23:45:10, finished=23:45:33, duration=22876ms, rate=17774 bytes/seg, state=1

**Comment by youngj** [comment] 2012-03-10 18:03
Perfect, that's exactly what I needed.

The app crashes there because the 'from' address of the IncomingMms is null. It seems that depending on timing, EnvayaSMS may attempt to read the sender address from the Android MMS database before it's written to the database. 

It seems a likely fix would be for MmsUtils.getMessagesInInbox() to skip the MMS if getSenderNumber(id) returns null. 

Although depending on whether Android notifies MmsUtils.OBSERVER_URI again, it may need to retry after a timeout.

**Comment by youngj** [comment] 2012-03-16 00:40
Fixed in version 2.0.5.

**Closed as completed by youngj** 2012-03-16 00:40 UTC
